-- ============================================================================
-- Somewhere for a box's total link, pictures and warnings to actually live.
--
-- Run once in the Supabase dashboard: SQL Editor -> New query -> Run.
-- Safe to run again. Nothing is deleted.
--
-- WHY THIS IS NEEDED
-- A box's total link is saved to two places today, and neither of them is shared:
--
--   1. localStorage, under kurdistani_box_links_cache — that is one browser, one phone.
--   2. The Apps Script, via action=get_box_links — which the deployed script does not
--      answer at all. Asked just now, the reply came back with only status, data and meta
--      and no box_links key.
--
-- So whoever saves a total link is the only person in the shop who can ever see it. The
-- pictures and the warning pictures attached to a box go the same way. That is the whole
-- complaint: the owner saves a link, and to everybody else the box looks empty.
--
-- Orders and gift cards already read from Supabase. This gives box links the same home, so
-- one person saving a link means every owner and admin can open it, copy it and edit it.
-- ============================================================================

create table if not exists public.box_links (
  id          bigint generated by default as identity primary key,
  /* Which box, in which month. A box name repeats across months, so neither alone is enough. */
  box_name    text not null,
  sheet_name  text not null,
  /* The SHEIN total-order link for the box. */
  total_link  text,
  /* Pictures of the box, and pictures of anything missing from it. */
  pictures    text[] not null default '{}',
  warnings    text[] not null default '{}',
  updated_at  timestamptz not null default now(),
  updated_by  uuid references public.profiles (id) on delete set null,
  updated_by_name text,
  /* One row per box per month, so saving twice edits rather than duplicates. */
  unique (sheet_name, box_name)
);

create index if not exists box_links_sheet_idx on public.box_links (sheet_name);

-- ----------------------------------------------------------------------------
-- Row level security
--
-- Reading is open to signed-in staff: a moderator packing a box needs to see its link and
-- its pictures. Writing is limited to the owner and admins, which is who manages the links.
-- ----------------------------------------------------------------------------

alter table public.box_links enable row level security;

revoke all on public.box_links from anon;
grant select, insert, update on public.box_links to authenticated;
-- No delete: a link is replaced by saving a new one, never removed.

do $$
declare
  p record;
begin
  for p in
    select policyname from pg_policies
    where schemaname = 'public' and tablename = 'box_links'
  loop
    execute format('drop policy %I on public.box_links', p.policyname);
  end loop;
end $$;

create policy "staff read box links"
  on public.box_links for select to authenticated
  using (true);

create policy "managers save box links"
  on public.box_links for insert to authenticated
  with check (public.is_gift_card_manager());

create policy "managers edit box links"
  on public.box_links for update to authenticated
  using (public.is_gift_card_manager())
  with check (public.is_gift_card_manager());

-- is_gift_card_manager() is reused rather than a second copy written: it already answers
-- "is this the owner or an admin", which is the same question here. It comes from
-- SETUP-ALL.sql; if that has not been run, run it first.

-- ----------------------------------------------------------------------------
-- Checks
-- ----------------------------------------------------------------------------

select column_name, data_type, is_nullable
from information_schema.columns
where table_schema = 'public' and table_name = 'box_links'
order by ordinal_position;

-- Expect three: one select for everyone signed in, insert and update for managers.
select policyname, cmd, roles from pg_policies
where schemaname = 'public' and tablename = 'box_links'
order by cmd, policyname;

select count(*) as box_links_so_far from public.box_links;
