-- ============================================================================
-- Give every gift card an id, and make the column look after itself from now on.
--
-- Run once in the Supabase dashboard: SQL Editor -> New query -> Run.
--
-- WHAT IS WRONG
-- gift_cards.id is a plain bigint with no default and no primary key, so the import wrote
-- 38 rows with no id at all. Only the original sample card has one. Two consequences:
--   - the app lists cards with key={card.id}, so 38 identical null keys means React cannot
--     tell the rows apart and the list misbehaves;
--   - nothing stops two cards ending up with the same id later.
--
-- Nothing here deletes or rewrites a card. Ids are filled in where they are missing, and
-- the column is then told to generate its own.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. Look before touching
-- ----------------------------------------------------------------------------

select
  count(*) as cards,
  count(id) as have_an_id,
  count(*) - count(id) as missing_an_id,
  coalesce(max(id), 0) as highest_id
from public.gift_cards;

-- ----------------------------------------------------------------------------
-- 2. Fill in the missing ids
--
-- Numbered oldest first so the ids run in the same order the cards were created, and
-- started above the highest id already in use so the sample card keeps its 1.
--
-- Matched on code rather than on ctid: code carries a unique index, which makes the join
-- exact. ctid is a physical location and can move under you.
--
-- The guard trigger does not object — it refuses changes to a card's code, its amount, or
-- an attempt to un-use it, and this changes none of those.
-- ----------------------------------------------------------------------------

with numbered as (
  select
    code,
    row_number() over (order by created_at nulls last, code)
      + coalesce((select max(id) from public.gift_cards), 0) as new_id
  from public.gift_cards
  where id is null
)
update public.gift_cards as g
  set id = numbered.new_id
  from numbered
  where g.code = numbered.code
    and g.id is null;

-- ----------------------------------------------------------------------------
-- 3. Make the column trustworthy
-- ----------------------------------------------------------------------------

alter table public.gift_cards alter column id set not null;

-- A primary key, if the table does not already have one.
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.gift_cards'::regclass and contype = 'p'
  ) then
    alter table public.gift_cards add constraint gift_cards_pkey primary key (id);
  end if;
end $$;

-- New rows get their own id. "by default" rather than "always", so a script may still
-- supply one explicitly when it needs to.
do $$
begin
  if not exists (
    select 1 from pg_attribute
    where attrelid = 'public.gift_cards'::regclass
      and attname = 'id'
      and attidentity <> ''
  ) then
    alter table public.gift_cards alter column id add generated by default as identity;
  end if;
end $$;

-- Start counting above the ids already in use, or the next insert collides with an
-- existing card.
select setval(
  pg_get_serial_sequence('public.gift_cards', 'id'),
  greatest(coalesce((select max(id) from public.gift_cards), 1), 1)
);

-- ----------------------------------------------------------------------------
-- 4. While we are here: take the delete privilege away properly
--
-- A moderator's delete already removes nothing, because no policy lets any row into a
-- delete's scope. But the table privilege itself was granted earlier and never withdrawn,
-- so the only thing standing in the way is the absence of a policy. Removing the privilege
-- as well means a permissive policy added by accident one day cannot open the door.
-- ----------------------------------------------------------------------------

revoke delete on public.gift_cards from authenticated;
revoke all on public.gift_cards from anon;

-- ----------------------------------------------------------------------------
-- 5. Checks — paste me this output
-- ----------------------------------------------------------------------------

-- Expect cards = have_an_id, missing_an_id = 0, and distinct_ids equal to cards.
select
  count(*) as cards,
  count(id) as have_an_id,
  count(*) - count(id) as missing_an_id,
  count(distinct id) as distinct_ids,
  min(id) as lowest_id,
  max(id) as highest_id
from public.gift_cards;

-- Expect is_identity = YES and is_nullable = NO.
select column_name, data_type, is_nullable, is_identity, identity_generation
from information_schema.columns
where table_schema = 'public' and table_name = 'gift_cards' and column_name = 'id';

-- Expect one primary key on (id).
select conname, pg_get_constraintdef(oid) as definition
from pg_constraint
where conrelid = 'public.gift_cards'::regclass and contype = 'p';

-- Expect select, insert, update for authenticated — and no delete, for anyone.
select grantee, privilege_type
from information_schema.role_table_grants
where table_schema = 'public' and table_name = 'gift_cards'
  and grantee in ('anon', 'authenticated')
order by grantee, privilege_type;
