import React, { useMemo, useState, useCallback, useRef, useEffect } from 'react';
import { Order, SCRIPT_URL, YEARS_CONFIG, getOrderStatus, STATUS_COLORS, getVerifiedSet, saveVerifiedSet, getMissingSet, saveMissingSet } from '@/types';
import { Package, Copy, Check, X, Download, Search, ChevronDown, ChevronUp, AlertTriangle, ShieldCheck, Heart, Plus, PackagePlus, Edit2, Pencil, Link2, ExternalLink, ImageIcon, Calendar, CheckCircle2 } from 'lucide-react';
import { PDFDocument } from 'pdf-lib';
import { getLinkedOrdersInfo, getDisplayPrice, getLinkedGroup } from '@/lib/order-utils';
import { fetchWithRetry } from '@/lib/fetchWithRetry';
import { sendNotification } from '@/lib/notifications';
import { SkuSearch } from './SkuSearch';

interface Props {
  orders: Order[];
  allOrders: Order[];
  onOrderClick: (order: Order) => void;
  viewingMonth: string;
  setViewingMonth: (m: string) => void;
  availableMonths: string[];
  activeYear: string;
  setActiveYear: (y: string) => void;
  onRefresh: () => void;
  onStatusChange: (order: Order, status: string) => void;
}

interface BoxGroup {
  box_name: string;
  orders: Order[];
  totalPieces: number;
  totalPrice: number;
  boxCost: number;
  shippingCost: number;
  lost: number;
  profit: number;
  isAutoGenerated: boolean;
  isBought: boolean;
  status: 'pending' | 'approved' | 'arrived' | 'cancelled';
  isFinished: boolean;
}

const BatchesView: React.FC<Props & { role?: string }> = ({ orders, allOrders, onOrderClick, onRefresh, onStatusChange, viewingMonth, setViewingMonth, availableMonths, activeYear, setActiveYear, role }) => {
  const [expandedBox, setExpandedBox] = useState<string | null>(null);
  const [editingField, setEditingField] = useState<{ box: string; field: string } | null>(null);
  const [fieldInput, setFieldInput] = useState('');
  const [boxFieldOverrides, setBoxFieldOverrides] = useState<Record<string, number>>({});
  const [finishedBoxOverrides, setFinishedBoxOverrides] = useState<Set<string>>(new Set());
  const [isSyncing, setIsSyncing] = useState(false);
  const [copiedBox, setCopiedBox] = useState<string | null>(null);
  const [isDownloading, setIsDownloading] = useState<string | null>(null);
  const [verifiedOrders, setVerifiedOrders] = useState<Set<string>>(getVerifiedSet);
  const [missingOrders, setMissingOrders] = useState<Set<string>>(getMissingSet);
  const [searchTerm, setSearchTerm] = useState('');
  const [creatingBox, setCreatingBox] = useState(false);
  const [selectedForBox, setSelectedForBox] = useState<Set<string>>(new Set());
  const [newBoxName, setNewBoxName] = useState('');
  const [createSearch, setCreateSearch] = useState('');
  const [showMonthPicker, setShowMonthPicker] = useState(false);
  const monthPickerRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const handle = (e: MouseEvent) => {
      if (monthPickerRef.current && !monthPickerRef.current.contains(e.target as Node)) setShowMonthPicker(false);
    };
    document.addEventListener('mousedown', handle);
    return () => document.removeEventListener('mousedown', handle);
  }, []);
  const [editingBoxPrice, setEditingBoxPrice] = useState<{ box: string; orderId: string | number } | null>(null);
  const [priceInput, setPriceInput] = useState('');
  const [renamingBox, setRenamingBox] = useState<string | null>(null);
  const [renameInput, setRenameInput] = useState('');

  const autoBoxCounter = useMemo(() => {
    const minBoxNum = 73;
    const nums = orders
      .filter(o => String(o.box_name || '').trim().match(/^Box \d+$/))
      .map(o => parseInt(String(o.box_name).replace('Box ', '')) || 0);
    return nums.length > 0 ? Math.max(minBoxNum - 1, ...nums) + 1 : minBoxNum;
  }, [orders]);

  const boxes = useMemo(() => {
    const map = new Map<string, Order[]>();
    
    // Pass 1: Find box names and propagate to linked orders within the same month
    const inheritedBoxNames = new Map<string, string>();
    orders.forEach(o => {
      const boxName = String(o.box_name || '').trim();
      if (boxName) {
        const group = getLinkedGroup(o, allOrders);
        group.forEach(lo => {
          // We only inherit if it's in the current month's "orders"
          const inCurrentMonth = orders.some(m => m.id === lo.id && m.sheet_name === lo.sheet_name);
          if (inCurrentMonth && !String(lo.box_name || '').trim()) {
            const key = `${lo.id}-${lo.sheet_name}`;
            inheritedBoxNames.set(key, boxName);
          }
        });
      }
    });

    // Pass 2: Group orders into boxes using actual or inherited box names
    orders.forEach(o => {
      const key = `${o.id}-${o.sheet_name}`;
      const boxName = String(o.box_name || '').trim() || inheritedBoxNames.get(key) || '';
      if (boxName) {
        map.set(boxName, [...(map.get(boxName) || []), o]);
      }
    });

    const result: BoxGroup[] = [];
    map.forEach((boxOrders, box_name) => {
      const totalPieces = boxOrders.reduce((s, o) => s + (Number(o.pics_text) || 0), 0);
      const totalPrice = boxOrders.reduce((s, o) => s + (parseFloat(String(o.price).replace(/[^0-9.-]+/g, '')) || 0), 0);
      const orderWithBoxCost = boxOrders.find(o => Number(String(o.box_cost || '').replace(/[^0-9.-]+/g, '')) > 0) || boxOrders[0];
      const boxCost = Number(String(orderWithBoxCost?.box_cost || '').replace(/[^0-9.-]+/g, '')) || 0;
      const orderWithShippingCost = boxOrders.find(o => Number(String(o.shipping_cost || '').replace(/[^0-9.-]+/g, '')) !== 0) || boxOrders[0];
      const shippingCost = Number(String(orderWithShippingCost?.shipping_cost || '').replace(/[^0-9.-]+/g, '')) || 0;
      const lostLevelOrder = boxOrders.find(o => Number(String(o.lost || '').replace(/[^0-9.-]+/g, '')) > 0) || boxOrders[0];
      const profitLevelOrder = boxOrders.find(o => Number(String(o.profit || '').replace(/[^0-9.-]+/g, '')) > 0) || boxOrders[0];
      const lost = Number(String(lostLevelOrder?.lost || '').replace(/[^0-9.-]+/g, '')) || 0;
      const profit = Number(String(profitLevelOrder?.profit || '').replace(/[^0-9.-]+/g, '')) || 0;
      const isAutoGenerated = /^Box[ -]\d+$/.test(box_name);

      // RULE: Box stays pending until ALL orders have a price in cell E
      const allHavePrice = boxOrders.every(o => {
        const p = parseFloat(String(o.price).replace(/[^0-9.-]+/g, '')) || 0;
        return p > 0;
      });
      let status: BoxGroup['status'] = 'pending';
      const extra = String(boxOrders[0]?.extra || '').trim();
      const match = extra.match(/\[(PENDING|APPROVED|ARRIVED|CANCELLED)\]/i);
      if (match) {
        // Only allow approved/arrived/cancelled if all orders have price
        const parsed = match[1].toLowerCase() as BoxGroup['status'];
        if (!allHavePrice && (parsed === 'approved' || parsed === 'arrived')) {
          status = 'pending'; // Override: can't be approved without prices
        } else {
          status = parsed;
        }
      }

      const isFinished = boxOrders.some(o => o.is_finished === true) || finishedBoxOverrides.has(box_name);
      result.push({ box_name, orders: boxOrders, totalPieces, totalPrice, boxCost, shippingCost, lost, profit, isAutoGenerated, isBought: boxCost > 0, status, isFinished });
    });

    return result.sort((a, b) => {
      if (a.isBought !== b.isBought) return a.isBought ? 1 : -1;
      
      const matchA = a.box_name.match(/\d+/);
      const matchB = b.box_name.match(/\d+/);
      const numA = matchA ? parseInt(matchA[0], 10) : NaN;
      const numB = matchB ? parseInt(matchB[0], 10) : NaN;
      
      const isNumA = !isNaN(numA);
      const isNumB = !isNaN(numB);
      
      if (isNumA && isNumB) {
        return numB - numA; // Descending purely numeric
      }
      
      // Fallback to text sorting, but still descending
      return b.box_name.localeCompare(a.box_name);
    });
  }, [orders, allOrders, finishedBoxOverrides]);

  const filteredBoxes = useMemo(() => {
    if (!searchTerm) return boxes;
    const q = searchTerm.toLowerCase();
    return boxes.filter(b => b.box_name.toLowerCase().includes(q) || b.orders.some(o => [o.name, o.insta, o.phone].some(f => String(f || '').toLowerCase().includes(q))));
  }, [boxes, searchTerm]);

  const unbatchedOrders = useMemo(() => {
    const unbatched: Order[] = [];
    const seenGroups = new Set<string>();
    
    // Filter orders where order.box_name is empty AND none of its linked group members have a box_name
    for (const o of orders) {
      if (String(o.box_name || '').trim()) continue;
      
      const group = getLinkedGroup(o, allOrders);
      if (group.some(lo => String(lo.box_name || '').trim())) continue;
      
      // Sort group so we consistently pick the same "parent" to receive the box explicitly
      group.sort((a, b) => {
        const idA = typeof a.id === 'string' ? parseInt(a.id) : Number(a.id);
        const idB = typeof b.id === 'string' ? parseInt(b.id) : Number(b.id);
        return idA - idB;
      });
      
      const parent = group[0];
      const parentKey = `${parent.id}-${parent.sheet_name}`;
      
      if (!seenGroups.has(parentKey)) {
        seenGroups.add(parentKey);
        // If this order IS the parent, include it in unbatched list
        if (parent.id === o.id && parent.sheet_name === o.sheet_name) {
          unbatched.push(o);
        }
      }
    }
    return unbatched;
  }, [orders, allOrders]);

  const filteredUnbatched = useMemo(() => {
    if (!createSearch) return unbatchedOrders;
    const q = createSearch.toLowerCase();
    return unbatchedOrders.filter(o => [o.name, o.insta, o.phone, o.place].some(f => String(f || '').toLowerCase().includes(q)));
  }, [unbatchedOrders, createSearch]);

  const toggleSelectOrder = (order: Order) => {
    const key = `${order.id}-${order.sheet_name}`;
    setSelectedForBox(prev => { const next = new Set(prev); if (next.has(key)) next.delete(key); else next.add(key); return next; });
  };

  const handleAutoBox = useCallback(async () => {
    if (unbatchedOrders.length === 0) return;
    setIsSyncing(true);
    try {
      let boxNum = autoBoxCounter;
      let currentBoxPieces = 0;
      // Check if the current box already has orders (from existing boxes)
      const existingBox = orders.filter(o => String(o.box_name || '').trim() === `Box ${boxNum - 1}`);
      if (existingBox.length > 0) {
        const existingPieces = existingBox.reduce((s, o) => s + (Number(o.pics_text) || 0), 0);
        if (existingPieces < 90) {
          boxNum = boxNum - 1;
          currentBoxPieces = existingPieces;
        }
      }

      const assignments: { order: Order; boxName: string }[] = [];
      for (const order of unbatchedOrders) {
        const pieces = Number(order.pics_text) || 1;
        // If adding this order would exceed 110 and we already have >= 90, start new box
        if (currentBoxPieces + pieces > 110 && currentBoxPieces >= 90) {
          boxNum++;
          currentBoxPieces = 0;
        }
        // If current box is already in range 90-110 and adding would exceed, start new box
        if (currentBoxPieces >= 90 && currentBoxPieces <= 110) {
          boxNum++;
          currentBoxPieces = 0;
        }
        assignments.push({ order, boxName: `Box ${boxNum}` });
        currentBoxPieces += pieces;
      }

      const bySheetBoxName = new Map<string, (string | number)[]>();
      for (const { order, boxName } of assignments) {
        const key = `${order.sheet_name}|${boxName}`;
        bySheetBoxName.set(key, [...(bySheetBoxName.get(key) || []), order.id]);
      }
      
      for (const [key, row_ids] of bySheetBoxName.entries()) {
        const [sheet, box_name] = key.split('|');
        await fetchWithRetry(SCRIPT_URL, { method: 'POST', body: JSON.stringify({ action: 'update_box_name', row_ids, sheet, box_name }) });
      }
      onRefresh();
    } catch (e) { console.error(e); }
    finally { setIsSyncing(false); }
  }, [unbatchedOrders, autoBoxCounter, orders, onRefresh]);

  const handleCreateBox = useCallback(async () => {
    if (!newBoxName.trim() || selectedForBox.size === 0) return;
    setIsSyncing(true);
    try {
      const sel = unbatchedOrders.filter(o => selectedForBox.has(`${o.id}-${o.sheet_name}`));
      const bySheet = new Map<string, (string | number)[]>();
      sel.forEach(order => {
        const sheet = order.sheet_name;
        bySheet.set(sheet, [...(bySheet.get(sheet) || []), order.id]);
      });
      
      for (const [sheet, row_ids] of bySheet.entries()) {
        await fetchWithRetry(SCRIPT_URL, { method: 'POST', body: JSON.stringify({ action: 'update_box_name', row_ids, sheet, box_name: newBoxName.trim() }) });
      }
      setCreatingBox(false); setSelectedForBox(new Set()); setNewBoxName(''); setCreateSearch('');
      onRefresh();
    } catch (e) { console.error(e); }
    finally { setIsSyncing(false); }
  }, [newBoxName, selectedForBox, unbatchedOrders, onRefresh]);

  const handleRenameBox = useCallback(async (box: BoxGroup) => {
    if (box.isFinished) return;
    if (!renameInput.trim() || renameInput.trim() === box.box_name) { setRenamingBox(null); return; }
    setIsSyncing(true);
    try {
      const bySheet = new Map<string, (string | number)[]>();
      box.orders.forEach(order => {
        const sheet = order.sheet_name;
        bySheet.set(sheet, [...(bySheet.get(sheet) || []), order.id]);
      });
      
      for (const [sheet, row_ids] of bySheet.entries()) {
        await fetchWithRetry(SCRIPT_URL, { method: 'POST', body: JSON.stringify({ action: 'update_box_name', row_ids, sheet, box_name: renameInput.trim() }) });
      }
      onRefresh();
    } catch (e) { console.error(e); }
    finally { setIsSyncing(false); setRenamingBox(null); }
  }, [renameInput, onRefresh]);

  const handleBoxStatusChange = useCallback(async (box: BoxGroup, newStatus: string) => {
    if (box.isFinished) return;
    // RULE: Can't approve/arrive a box if any order is missing price (cell E)
    if (newStatus === 'approved' || newStatus === 'arrived') {
      const allHavePrice = box.orders.every(o => {
        const p = parseFloat(String(o.price).replace(/[^0-9.-]+/g, '')) || 0;
        return p > 0;
      });
      if (!allHavePrice) {
        alert('Cannot set box to ' + newStatus + '. All orders must have a price (cell E) first.');
        return;
      }
    }
    setIsSyncing(true);
    try {
      for (const order of box.orders) {
        await onStatusChange(order, newStatus);
      }
      if (newStatus === 'approved') {
        const role = localStorage.getItem('auth_role') || 'unknown';
        const instas = Array.from(new Set(box.orders.map(o => o.insta || 'Unknown'))).filter(i => i !== 'Unknown');
        const boxName = box.box_name || 'Unnamed Box';
        sendNotification('approve', `Box approved: ${boxName}\nUsers: ${instas.join(', ')}`, role);
      }
    } catch (e) { console.error(e); }
    finally { setIsSyncing(false); }
  }, [onStatusChange]);

  const handleSaveField = useCallback(async (box: BoxGroup, field: string) => {
    if (box.isFinished) return;
    const value = Number(fieldInput.replace(/[^0-9.-]+/g, '')) || 0;
    setBoxFieldOverrides(prev => ({ ...prev, [`${box.box_name}|${field}`]: value }));
    setEditingField(null);
    setFieldInput('');

    const idsBySheet = new Map<string, (string | number)[]>();
    box.orders.forEach((order, index) => {
      const sheet = order.sheet_name;
      (order as any)[field] = index === 0 ? (value || '') : '';
      idsBySheet.set(sheet, [...(idsBySheet.get(sheet) || []), order.id]);
    });

    Promise.all(Array.from(idsBySheet.entries()).map(([sheet, row_ids]) =>
      fetchWithRetry(SCRIPT_URL, {
        method: 'POST',
        body: JSON.stringify({ action: 'update_box_field_once', field, row_ids, sheet, value: value || '' })
      })
    )).then(onRefresh).catch(e => console.error(e));
  }, [fieldInput, onRefresh]);

  const handleSaveOrderPrice = useCallback(async (order: Order) => {
    if (order.is_finished) return;
    const newPrice = Number(priceInput.replace(/[^0-9.-]+/g, '')) || 0;
    setIsSyncing(true);
    try {
      order.price = newPrice; // Optimistic
      await fetchWithRetry(SCRIPT_URL, {
        method: 'POST',
        body: JSON.stringify({ action: 'update_price', sheet: order.sheet_name, row_id: order.id, value: newPrice || '' })
      });
      onRefresh();
    } catch (e) { console.error(e); }
    finally { setIsSyncing(false); setEditingBoxPrice(null); }
  }, [priceInput, onRefresh]);

  const handleFinishBox = useCallback(async (box: BoxGroup) => {
    if (role !== 'owner') return;
    setFinishedBoxOverrides(prev => new Set(prev).add(box.box_name));
    setIsSyncing(true);
    try {
      const bySheet = new Map<string, (string | number)[]>();
      box.orders.forEach(order => {
        order.is_finished = true;
        bySheet.set(order.sheet_name, [...(bySheet.get(order.sheet_name) || []), order.id]);
      });
      for (const [sheet, row_ids] of bySheet.entries()) {
        await fetchWithRetry(SCRIPT_URL, {
          method: 'POST',
          body: JSON.stringify({ action: 'mark_box_finished', sheet, row_ids, finished: true })
        });
      }
      onRefresh();
    } catch (e) { console.error(e); }
    finally { setIsSyncing(false); }
  }, [role, onRefresh]);

  const handleVerify = (order: Order) => {
    if (order.is_finished) return;
    const key = `${order.id}-${order.sheet_name}`;
    const next = new Set(verifiedOrders);
    if (next.has(key)) next.delete(key); else next.add(key);
    setVerifiedOrders(next); saveVerifiedSet(next);
    fetchWithRetry(SCRIPT_URL, { method: 'POST', body: JSON.stringify({ action: 'verifyOrder', row_id: order.id, sheet_name: order.sheet_name, matchStatus: next.has(key) ? 'match' : 'mismatch' }) }).catch(() => {});
  };

  const handleMissing = (order: Order) => {
    if (order.is_finished) return;
    const key = `${order.id}-${order.sheet_name}`;
    const next = new Set(missingOrders);
    if (next.has(key)) next.delete(key); else next.add(key);
    setMissingOrders(next); saveMissingSet(next);
    fetchWithRetry(SCRIPT_URL, { method: 'POST', body: JSON.stringify({ action: 'markMissing', row_id: order.id, sheet_name: order.sheet_name, missing: next.has(key) }) }).catch(() => {});
  };

  const handleEditOrderBox = async (order: Order) => {
    if (order.is_finished) return;
    const currentBox = String(order.box_name || '').trim();
    const newBox = window.prompt(`Change Box Name for ${order.name || order.insta || '-'}:`, currentBox);
    if (newBox !== null && newBox.trim() !== currentBox) {
      const trimmed = newBox.trim();
      try {
        await fetchWithRetry(SCRIPT_URL, {
          method: 'POST',
          body: JSON.stringify({
            action: 'update_box_name',
            row_id: order.id,
            sheet: order.sheet_name,
            box_name: trimmed
          })
        });
        order.box_name = trimmed; // optimistic update
      } catch (err) {
        alert('Failed to update box name');
      }
    }
  };

  const copyBox = (box: BoxGroup) => {
    const text = box.orders.map((o, i) => {
      const rawPrice = parseFloat(String(o.price).replace(/[^0-9.-]+/g, '')) || 0;
      return `${i + 1}. ${o.name || o.insta} - ${o.place || '-'} - ${rawPrice.toLocaleString()} IQD`;
    }).join('\n');
    navigator.clipboard.writeText(`📦 ${box.box_name}\nPieces: ${box.totalPieces}\n${text}\n\nTotal: ${box.totalPrice.toLocaleString()} IQD`);
    setCopiedBox(box.box_name); setTimeout(() => setCopiedBox(null), 2000);
  };

  const handleDownloadAllPdfs = async (box: BoxGroup) => {
    if (isDownloading) return;
    setIsDownloading(box.box_name);
    try {
      const { generateBatchPdf } = await import('@/lib/pdf');
      generateBatchPdf(box.box_name, box.orders, allOrders);
    } catch (e) { console.error(e); }
    finally { setIsDownloading(null); }
  };

  const stats = useMemo(() => ({
    total: boxes.length,
    pending: boxes.filter(b => !b.isBought).length,
    bought: boxes.filter(b => b.isBought).length,
    totalPieces: boxes.reduce((s, b) => s + b.totalPieces, 0),
    totalValue: boxes.reduce((s, b) => s + b.totalPrice, 0),
    unbatched: unbatchedOrders.length,
  }), [boxes, unbatchedOrders]);

  const EditableField = ({ box, field, label, value, colorClass }: { box: BoxGroup; field: string; label: string; value: number; colorClass?: string }) => {
    const displayValue = boxFieldOverrides[`${box.box_name}|${field}`] ?? value;
    return (
      <div className={`bg-card p-2.5 rounded-lg border border-border ${colorClass || ''}`}>
        <div className="text-[10px] text-muted-foreground font-semibold uppercase mb-1">{label}</div>
        {editingField?.box === box.box_name && editingField?.field === field ? (
          <div className="flex gap-1">
            <input value={fieldInput} onChange={e => setFieldInput(e.target.value)} className="w-full bg-secondary border border-border rounded px-2 py-1.5 text-base sm:text-xs" inputMode="decimal" autoFocus onFocus={e => e.currentTarget.select()} onKeyDown={e => { if (e.key === 'Enter') handleSaveField(box, field); if (e.key === 'Escape') setEditingField(null); }} />
            <button onClick={() => handleSaveField(box, field)} className="text-primary"><Check size={14} /></button>
            <button onClick={() => setEditingField(null)} className="text-muted-foreground"><X size={14} /></button>
          </div>
        ) : (
          <button disabled={box.isFinished} onClick={() => { setEditingField({ box: box.box_name, field }); setFieldInput(String(displayValue || '')); }} className={`text-sm font-bold hover:opacity-80 transition-colors flex items-center gap-1 disabled:cursor-not-allowed disabled:opacity-70 ${field === 'lost' ? 'text-destructive' : field === 'profit' ? 'text-primary' : ''}`}>
            {displayValue > 0 ? `${displayValue.toLocaleString()} IQD` : 'Set'} {!box.isFinished && <Edit2 size={10} />}
          </button>
        )}
      </div>
    );
  };

  return (
    <div className="space-y-4 animate-slide-up">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold">Boxes</h1>
          <p className="text-sm text-muted-foreground">{stats.total} active boxes • {stats.totalPieces} items • {(stats.totalValue / 1000).toFixed(0)}K IQD</p>
        </div>
        <div className="flex flex-wrap items-center gap-2">
          <div ref={monthPickerRef} className="relative">
            <button onClick={() => setShowMonthPicker(p => !p)} className="flex items-center gap-1.5 bg-secondary text-foreground px-3 py-2 rounded-full text-sm font-semibold hover:bg-secondary/80 transition-all border border-border">
              <Calendar size={14} /> {viewingMonth || activeYear}
              <ChevronDown size={12} className={`transition-transform ${showMonthPicker ? 'rotate-180' : ''}`} />
            </button>
            {showMonthPicker && (
              <div className="absolute right-0 mt-2 bg-card border border-border rounded-xl shadow-lg z-50 p-2 min-w-[140px]">
                <div className="flex gap-1 px-1 pb-2 border-b border-border mb-2">
                  {Object.keys(YEARS_CONFIG).sort((a, b) => b.localeCompare(a)).map(y => (
                    <button key={y} onClick={() => setActiveYear(y)} className={`px-2 py-1 rounded text-[10px] font-bold transition-all ${activeYear === y ? 'bg-primary text-primary-foreground' : 'bg-secondary text-muted-foreground hover:text-foreground'}`}>
                      {y}
                    </button>
                  ))}
                </div>
                <div className="flex flex-col gap-0.5">
                  {availableMonths.map(m => (
                    <button key={m} onClick={() => { setViewingMonth(m); setShowMonthPicker(false); }} className={`text-left px-2.5 py-1.5 rounded-lg text-xs font-medium transition-all ${viewingMonth === m ? 'bg-primary text-primary-foreground' : 'hover:bg-secondary'}`}>
                      {m}
                    </button>
                  ))}
                </div>
              </div>
            )}
          </div>
          <SkuSearch orders={allOrders} onFound={onOrderClick} />
          <button onClick={() => setCreatingBox(true)} className="flex items-center gap-1.5 bg-primary text-primary-foreground px-4 py-2 rounded-full text-sm font-semibold hover:bg-primary/90 transition-all glow-primary">
            <Plus size={14} /> New Box
          </button>
          {unbatchedOrders.length > 0 && (
            <button onClick={handleAutoBox} disabled={isSyncing} className="flex items-center gap-1.5 bg-accent text-accent-foreground px-3 py-2 rounded-full text-sm font-semibold hover:bg-accent/90 transition-all disabled:opacity-50">
              <PackagePlus size={14} /> Auto ({unbatchedOrders.length})
            </button>
          )}
        </div>
      </div>
      
      <div className="relative">
        <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" size={14} />
        <input value={searchTerm} onChange={e => setSearchTerm(e.target.value)} placeholder="Search boxes..." className="w-full bg-secondary border border-border rounded-lg pl-9 pr-3 py-2 text-sm focus:outline-none focus:border-primary/50" />
      </div>

      {unbatchedOrders.length > 0 && !creatingBox && (
        <div className="bg-amber-50 dark:bg-amber-500/10 border border-amber-200 dark:border-amber-500/20 rounded-xl p-3 flex items-center gap-3">
          <AlertTriangle size={16} className="text-amber-500 shrink-0" />
          <div className="flex-1">
            <span className="text-sm font-semibold text-amber-700 dark:text-amber-400">{unbatchedOrders.length} orders without a box</span>
            <p className="text-xs text-amber-600 dark:text-amber-500">Click "Auto Box" to automatically assign each order its own box</p>
          </div>
        </div>
      )}

      {creatingBox && (
        <div className="bg-card border border-primary/20 rounded-xl p-4 space-y-3 animate-slide-up">
          <div className="flex items-center justify-between">
            <h3 className="font-bold text-sm">Create New Box</h3>
            <button onClick={() => { setCreatingBox(false); setSelectedForBox(new Set()); }} className="text-muted-foreground hover:text-foreground"><X size={16} /></button>
          </div>
          <input value={newBoxName} onChange={e => setNewBoxName(e.target.value)} placeholder="Box name (e.g. Box 5)" className="w-full bg-secondary border border-border rounded-lg px-3 py-2 text-sm focus:outline-none focus:border-primary/50" />
          <input value={createSearch} onChange={e => setCreateSearch(e.target.value)} placeholder="Search unbatched orders..." className="w-full bg-secondary border border-border rounded-lg px-3 py-2 text-sm focus:outline-none focus:border-primary/50" />
          <div className="max-h-48 overflow-y-auto space-y-1 custom-scrollbar">
            {filteredUnbatched.map(o => {
              const key = `${o.id}-${o.sheet_name}`;
              const linkedOrders = getLinkedGroup(o, allOrders).filter(lo => lo.id !== o.id || lo.sheet_name !== o.sheet_name);
              const rawCombinedPrice = [o, ...linkedOrders].reduce((sum, lo) => sum + (parseFloat(String(lo.price).replace(/[^0-9.-]+/g, '')) || 0), 0);
              return (
                <button key={key} onClick={() => toggleSelectOrder(o)} className={`w-full flex items-center gap-2 px-3 py-2 rounded-lg text-left text-sm transition-all ${selectedForBox.has(key) ? 'bg-primary/10 border border-primary/30' : 'bg-secondary hover:bg-secondary/80 border border-transparent'}`}>
                  <div className={`w-4 h-4 rounded border flex items-center justify-center ${selectedForBox.has(key) ? 'bg-primary border-primary' : 'border-border'}`}>
                    {selectedForBox.has(key) && <Check size={10} className="text-primary-foreground" />}
                  </div>
                  <span className="font-medium truncate">{o.name || o.insta}</span>
                  {linkedOrders.length > 0 && <Link2 size={12} className="text-primary" />}
                  <span className="text-muted-foreground text-xs ml-auto">{rawCombinedPrice.toLocaleString()} IQD</span>
                </button>
              );
            })}
          </div>
          <button onClick={handleCreateBox} disabled={!newBoxName.trim() || selectedForBox.size === 0 || isSyncing} className="w-full bg-primary text-primary-foreground py-2.5 rounded-lg font-semibold text-sm disabled:opacity-50 transition-all">
            {isSyncing ? 'Creating...' : `Create Box (${selectedForBox.size} orders)`}
          </button>
        </div>
      )}

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {filteredBoxes.map(box => {
          const isExpanded = expandedBox === box.box_name;
          const numMatch = box.box_name.match(/(\d+)/);
          const displayName = numMatch ? numMatch[1] : box.box_name;
          return (
            <div key={box.box_name} className={`border rounded-xl overflow-hidden transition-all ${box.isFinished ? 'bg-orange-100 border-orange-400 shadow-sm ring-1 ring-orange-300 dark:bg-orange-500/15 dark:border-orange-400/60 dark:ring-orange-500/30' : box.isBought ? 'bg-card border-primary/20' : 'bg-card border-border'}`}>
              <div 
                className="p-4 pb-2 cursor-pointer select-none"
                onClick={(e) => {
                  const target = e.target as HTMLElement;
                  if (!target.closest('button') && !target.closest('input')) {
                    setExpandedBox(isExpanded ? null : box.box_name);
                  }
                }}
              >
                <div className="flex items-center justify-between mb-2">
                  <div className="flex items-center gap-3">
                    <div className={`w-10 h-10 rounded-xl flex items-center justify-center ${box.isFinished ? 'bg-orange-500 text-white shadow-sm dark:bg-orange-500 dark:text-white' : box.isBought ? 'bg-primary/10 text-primary' : 'bg-amber-50 text-amber-500 dark:bg-amber-500/10'}`}>
                      <Package size={20} />
                    </div>
                    <div>
                      {renamingBox === box.box_name ? (
                        <div className="flex items-center gap-1">
                          <input value={renameInput} onChange={e => setRenameInput(e.target.value)} className="bg-secondary border border-border rounded px-2 py-1 text-sm font-bold w-32" autoFocus onKeyDown={e => { if (e.key === 'Enter') handleRenameBox(box); if (e.key === 'Escape') setRenamingBox(null); }} />
                          <button onClick={() => handleRenameBox(box)} className="text-primary"><Check size={14} /></button>
                          <button onClick={() => setRenamingBox(null)} className="text-muted-foreground"><X size={14} /></button>
                        </div>
                      ) : (
                        <div className="flex items-center gap-1.5">
                          <span className="font-bold text-xl">{displayName}</span>
                          {box.isFinished && <span className="rounded-full bg-orange-200 px-2 py-0.5 text-[10px] font-bold uppercase text-orange-800 dark:bg-orange-500/20 dark:text-orange-300">Finished</span>}
                          {!box.isFinished && (
                            <button onClick={(e) => { e.stopPropagation(); setRenamingBox(box.box_name); setRenameInput(box.box_name); }} className="p-1 rounded hover:bg-secondary text-muted-foreground hover:text-foreground transition-all">
                              <Pencil size={12} />
                            </button>
                          )}
                        </div>
                      )}
                      {/* Box status buttons */}
                      <div className="flex items-center gap-1 mt-1">
                        {(['pending', 'approved', 'arrived', 'cancelled'] as const).map(s => (
                          <button key={s} disabled={box.isFinished} onClick={() => handleBoxStatusChange(box, s)} className={`px-1.5 py-0.5 rounded text-[10px] font-semibold border transition-all disabled:cursor-not-allowed disabled:opacity-70 ${box.status === s ? STATUS_COLORS[s] : 'bg-secondary text-muted-foreground border-transparent hover:border-border'}`}>
                            {s.charAt(0).toUpperCase() + s.slice(1)}
                          </button>
                        ))}
                      </div>
                    </div>
                  </div>
                  <div className="flex items-center gap-1.5">
                    <button onClick={e => { e.stopPropagation(); copyBox(box); }} className="p-1.5 rounded-lg text-muted-foreground hover:text-foreground hover:bg-secondary transition-all">
                      {copiedBox === box.box_name ? <Check size={16} /> : <Copy size={16} />}
                    </button>
                    {role === 'owner' && (
                      <button onClick={e => { e.stopPropagation(); handleFinishBox(box); }} disabled={isSyncing || box.isFinished} className={`p-1.5 rounded-lg transition-all disabled:cursor-not-allowed ${box.isFinished ? 'bg-orange-500 text-white opacity-100 shadow-sm' : 'text-orange-700 hover:bg-orange-100 dark:text-orange-300 dark:hover:bg-orange-500/10 disabled:opacity-50'}`} title="Mark box finished">
                        <CheckCircle2 size={16} />
                      </button>
                    )}
                    <button onClick={(e) => { e.stopPropagation(); setExpandedBox(isExpanded ? null : box.box_name); }} className="p-2 rounded-lg text-muted-foreground hover:text-foreground hover:bg-secondary transition-all">
                      {isExpanded ? <ChevronUp size={20} /> : <ChevronDown size={20} />}
                    </button>
                  </div>
                </div>

                <div className="grid grid-cols-3 gap-2 mt-3">
                  <div className={`${box.isFinished ? 'bg-orange-200/70 dark:bg-orange-500/15' : 'bg-secondary'} rounded-xl py-3 text-center`}>
                    <div className="text-lg font-bold">{box.orders.length}</div>
                    <div className="text-[10px] text-muted-foreground font-medium">Orders</div>
                  </div>
                  <div className={`${box.isFinished ? 'bg-orange-200/70 dark:bg-orange-500/15' : 'bg-secondary'} rounded-xl py-3 text-center`}>
                    <div className="text-lg font-bold">{box.totalPieces}</div>
                    <div className="text-[10px] text-muted-foreground font-medium">Items</div>
                  </div>
                  <div className={`${box.isFinished ? 'bg-orange-200/70 dark:bg-orange-500/15' : 'bg-secondary'} rounded-xl py-3 text-center`}>
                    <div className="text-base font-bold tabular-nums">{box.totalPrice.toLocaleString()}</div>
                    <div className="text-[10px] text-muted-foreground font-medium">IQD Total</div>
                  </div>
                </div>
              </div>

              {(box.lost > 0 || box.profit > 0) && (
                <div className="px-4 pb-3 flex gap-3">
                  {box.lost > 0 && <span className="text-xs text-destructive font-medium">Lost: {box.lost.toLocaleString()}</span>}
                  {box.profit > 0 && <span className="text-xs text-primary font-medium">Profit: {box.profit.toLocaleString()}</span>}
                </div>
              )}

              {isExpanded && (
                <div className="border-t border-border">
                  <div className={`grid grid-cols-2 sm:grid-cols-4 gap-2 p-3 ${box.isFinished ? 'bg-orange-100/80 dark:bg-orange-500/10' : 'bg-secondary/30'}`}>
                    <EditableField box={box} field="box_cost" label="Box Cost (F)" value={box.boxCost} />
                    <EditableField box={box} field="shipping_cost" label="Shipping (H)" value={box.shippingCost} />
                    <EditableField box={box} field="lost" label="Lost 60% (K)" value={box.lost} colorClass="bg-red-50/50 dark:bg-red-500/5" />
                    <EditableField box={box} field="profit" label="Profit 40% (L)" value={box.profit} colorClass="bg-emerald-50/50 dark:bg-emerald-500/5" />
                  </div>

                  <div className={`flex items-center gap-2 p-3 border-t border-border ${box.isFinished ? 'bg-orange-100/70 dark:bg-orange-500/10' : 'bg-secondary/20'}`}>
                    <button onClick={() => handleDownloadAllPdfs(box)} disabled={!!isDownloading} className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-secondary text-sm font-medium hover:bg-secondary/80 transition-all">
                      {isDownloading === box.box_name ? <div className="w-3 h-3 border-2 border-primary border-t-transparent rounded-full animate-spin" /> : <Download size={14} />}
                      Download All PDFs
                    </button>
                  </div>

                  <div className="divide-y divide-border">
                    {box.orders.map(order => {
                      const key = `${order.id}-${order.sheet_name}`;
                      const isVerified = verifiedOrders.has(key);
                      const isMissing = missingOrders.has(key);
                      const orderStatus = getOrderStatus(order);
                      const linkedOrders = getLinkedGroup(order, allOrders).filter(o => o.id !== order.id || o.sheet_name !== order.sheet_name);
                      const rawCombinedPrice = [order, ...linkedOrders].reduce((sum, o) => sum + (parseFloat(String(o.price).replace(/[^0-9.-]+/g, '')) || 0), 0);
                      
                      return (
                        <div key={key} className={`p-3 flex items-center gap-2 transition-colors ${box.isFinished ? 'bg-orange-50/80 hover:bg-orange-100 dark:bg-orange-500/5 dark:hover:bg-orange-500/10' : 'hover:bg-secondary/30'} ${isMissing ? 'bg-amber-50/50 dark:bg-amber-500/5' : ''}`}>
                          <button disabled={order.is_finished} onClick={() => handleMissing(order)} className={`shrink-0 w-4 h-4 rounded flex items-center justify-center transition-all disabled:cursor-not-allowed disabled:opacity-50 ${isMissing ? 'bg-amber-400 text-white' : 'bg-secondary text-muted-foreground hover:text-amber-500'}`}>
                            <AlertTriangle size={10} />
                          </button>
                          <div className="flex-1 min-w-0 cursor-pointer" onClick={() => onOrderClick(order)}>
                            <div className="flex items-center gap-2">
                              <span className="font-bold text-[14px] truncate">@{order.insta || order.name || 'Unknown'} {linkedOrders.length > 0 && <Link2 size={10} className="inline text-primary ml-1" />}</span>
                              {String(order.primary_urls || '').trim() && (
                                <span title="Has primary picture" className="shrink-0 inline-flex items-center justify-center w-5 h-5 rounded-full bg-primary/15 text-primary border border-primary/30">
                                  <ImageIcon size={11} />
                                </span>
                              )}
                            </div>
                            <div className="text-[11px] text-muted-foreground flex items-center mt-0.5">
                              <span>{order.pics_text || 1} pcs</span>
                            </div>
                          </div>
                          
                          <div className="flex items-center gap-3 sm:gap-4 shrink-0 pr-1">
                            {order.link && (
                              <a href={String(order.link).startsWith('http') ? order.link : `https://${order.link}`} target="_blank" rel="noopener noreferrer" className="w-8 h-8 rounded-full bg-[#0cbaba] text-white hover:bg-[#0aa3a3] transition-colors flex items-center justify-center shadow-sm" onClick={e => e.stopPropagation()} title="Product Link">
                                <ExternalLink size={16} />
                              </a>
                            )}
                            <div className="flex flex-col items-center justify-center gap-2">
                              <select disabled={order.is_finished} value={orderStatus} onChange={e => { e.stopPropagation(); onStatusChange(order, e.target.value); }} className="bg-transparent text-[16px] border-none focus:outline-none text-muted-foreground cursor-pointer disabled:cursor-not-allowed disabled:opacity-50 w-6 appearance-none text-center p-0 m-0 leading-none" onClick={e => e.stopPropagation()}>
                                <option value="pending">⏳</option>
                                <option value="approved">✅</option>
                                <option value="arrived">📦</option>
                                <option value="cancelled">❌</option>
                              </select>
                              <button disabled={order.is_finished} onClick={() => handleVerify(order)} className={`p-1 transition-all flex items-center justify-center disabled:cursor-not-allowed disabled:opacity-50 ${isVerified ? 'text-primary' : 'text-muted-foreground hover:text-primary'}`}>
                                <Heart size={16} fill={isVerified ? 'currentColor' : 'none'} />
                              </button>
                            </div>

                            <div className="flex flex-col items-end justify-center min-w-[55px]">
                              {editingBoxPrice?.box === box.box_name && editingBoxPrice?.orderId === order.id ? (
                                <div className="flex gap-1 items-center">
                                  <input value={priceInput} onChange={e => setPriceInput(e.target.value)} className="w-24 bg-secondary border border-border rounded px-2 py-1.5 text-base sm:text-xs text-right" inputMode="decimal" autoFocus onFocus={e => e.currentTarget.select()} onKeyDown={e => { if (e.key === 'Enter') handleSaveOrderPrice(order); if (e.key === 'Escape') setEditingBoxPrice(null); }} onClick={e => e.stopPropagation()} />
                                  <button onClick={(e) => { e.stopPropagation(); handleSaveOrderPrice(order); }} className="text-primary"><Check size={12} /></button>
                                  <button onClick={(e) => { e.stopPropagation(); setEditingBoxPrice(null); }} className="text-muted-foreground"><X size={12} /></button>
                                </div>
                              ) : (
                                <div className={`font-bold text-[14px] leading-none tracking-tight ${order.is_finished ? 'cursor-default opacity-80' : 'cursor-pointer hover:opacity-80'}`} onClick={e => { e.stopPropagation(); if (!order.is_finished) { setEditingBoxPrice({ box: box.box_name, orderId: order.id }); setPriceInput(String(rawCombinedPrice)); } }}>
                                  {rawCombinedPrice > 0 ? rawCombinedPrice.toLocaleString() : 'Set'}
                                </div>
                              )}
                            </div>
                          </div>
                        </div>
                      );
                    })}
                  </div>
                </div>
              )}
            </div>
          );
        })}
      </div>

      {filteredBoxes.length === 0 && !creatingBox && (
        <div className="py-16 text-center">
          <Package size={40} className="mx-auto text-muted-foreground/30 mb-3" />
          <p className="text-muted-foreground font-medium text-sm">No boxes found</p>
        </div>
      )}
    </div>
  );
};

export default BatchesView;
